const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Milan Maniya";
const email = 'Email';
const emailHint = 'milan@gmail.com';
const password = 'Password';
const passwordHint = '********';
const forgotPassword = 'Forgot Password';
const login = 'Login';
const signup = 'Sign up';
const createNewAccount = 'or, create a new account';
const loginWith = 'Login with';
const name = 'Name';
const retypePassword = 'Retype Password';
const nameHint = 'milan maniya';
const privacyPolicy = 'Privacy Policy';
const termsCondition = 'Terms and Conditions';
const alreadyHaveAnAccount = 'Already have an account? ';

const home = 'Home',
    categories = 'Categrories',
    cart = 'Cart',
    account = 'Account';

const searchAnything = 'Search Anything...',
    todayDeal = "Today's Deal",
    flashSale = 'Flash Sale',
    topBrand = 'Top Brand',
    topSeller = 'Top Seller',
    topCategories = 'Top Categories',
    womenDress = 'Women Dress',
    girlsWatches = 'Girls Watches',
    mobilePhone = 'Mobile Phone',
    boysGlasses = 'Boys Glasses',
    tShrirts = 'TShirts',
    featuredProduct = 'Featured Product',
    girlsDress = 'Girls Dress',
    featuredCategories = 'Fetured Categories';
