const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Milan Maniya";
const email = 'Email';
const emailHint = 'milan@gmail.com';
const password = 'Password';
const passwordHint = '********';
const forgotPassword = 'Forgot Password';
const login = 'Login';
const signup = 'Sign up';
const createNewAccount = 'or, create a new account';
const loginWith = 'Login with';
const name = 'Name';
const retypePassword = 'Retype Password';
const nameHint = 'milan maniya';
const privacyPolicy = 'Privacy Policy';
const termsCondition = 'Terms and Conditions';
const alreadyHaveAnAccount = 'Already have an account? ';

const home = 'Home',
    categories = 'Categrories',
    cart = 'Cart',
    account = 'Account';
